# Timeout in seconds before auto-boot.
timeout: 0
# Entry name shown in the boot menu. The leading slash is required.
#/My OS
/My OS
	# Use the Limine boot protocol for our kernel.
	protocol: limine
	# Path to the kernel file relative to the partition containing limine.conf.
	# We copy the kernel as "myos" into /boot in the ISO, so:
	path: boot():/boot/myos
	module_path: boot():/boot/init.elf
	module_path: boot():/boot/wallpaper.raw